//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitorRegistration.Web.VisitorRegistrationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Visitor", Namespace="http://schemas.datacontract.org/2004/07/VisitorRegistration.Wcf")]
    [System.SerializableAttribute()]
    public partial class Visitor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfVisitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VisitorRegistration.Web.VisitorRegistrationService.File[] FilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> PrintedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] VisitorPassField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfVisit {
            get {
                return this.DateOfVisitField;
            }
            set {
                if ((this.DateOfVisitField.Equals(value) != true)) {
                    this.DateOfVisitField = value;
                    this.RaisePropertyChanged("DateOfVisit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VisitorRegistration.Web.VisitorRegistrationService.File[] Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HostEmail {
            get {
                return this.HostEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.HostEmailField, value) != true)) {
                    this.HostEmailField = value;
                    this.RaisePropertyChanged("HostEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDNumber {
            get {
                return this.IDNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IDNumberField, value) != true)) {
                    this.IDNumberField = value;
                    this.RaisePropertyChanged("IDNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Printed {
            get {
                return this.PrintedField;
            }
            set {
                if ((this.PrintedField.Equals(value) != true)) {
                    this.PrintedField = value;
                    this.RaisePropertyChanged("Printed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] VisitorPass {
            get {
                return this.VisitorPassField;
            }
            set {
                if ((object.ReferenceEquals(this.VisitorPassField, value) != true)) {
                    this.VisitorPassField = value;
                    this.RaisePropertyChanged("VisitorPass");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="File", Namespace="http://schemas.datacontract.org/2004/07/VisitorRegistration.Wcf")]
    [System.SerializableAttribute()]
    public partial class File : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VisitorRegistration.Web.VisitorRegistrationService.Visitor VisitorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VisitorIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileUrl {
            get {
                return this.FileUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.FileUrlField, value) != true)) {
                    this.FileUrlField = value;
                    this.RaisePropertyChanged("FileUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VisitorRegistration.Web.VisitorRegistrationService.Visitor Visitor {
            get {
                return this.VisitorField;
            }
            set {
                if ((object.ReferenceEquals(this.VisitorField, value) != true)) {
                    this.VisitorField = value;
                    this.RaisePropertyChanged("Visitor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VisitorID {
            get {
                return this.VisitorIDField;
            }
            set {
                if ((this.VisitorIDField.Equals(value) != true)) {
                    this.VisitorIDField = value;
                    this.RaisePropertyChanged("VisitorID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VisitorRegistrationService.IEndpoint")]
    public interface IEndpoint {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndpoint/RegisterVisitor", ReplyAction="http://tempuri.org/IEndpoint/RegisterVisitorResponse")]
        void RegisterVisitor(string FirstName, string LastName, string Email, string HostEmail, string IDNumber, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndpoint/RegisterVisitor", ReplyAction="http://tempuri.org/IEndpoint/RegisterVisitorResponse")]
        System.Threading.Tasks.Task RegisterVisitorAsync(string FirstName, string LastName, string Email, string HostEmail, string IDNumber, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndpoint/GetVisitor", ReplyAction="http://tempuri.org/IEndpoint/GetVisitorResponse")]
        VisitorRegistration.Web.VisitorRegistrationService.Visitor GetVisitor(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndpoint/GetVisitor", ReplyAction="http://tempuri.org/IEndpoint/GetVisitorResponse")]
        System.Threading.Tasks.Task<VisitorRegistration.Web.VisitorRegistrationService.Visitor> GetVisitorAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndpoint/GetCurrentVisitors", ReplyAction="http://tempuri.org/IEndpoint/GetCurrentVisitorsResponse")]
        VisitorRegistration.Web.VisitorRegistrationService.Visitor[] GetCurrentVisitors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndpoint/GetCurrentVisitors", ReplyAction="http://tempuri.org/IEndpoint/GetCurrentVisitorsResponse")]
        System.Threading.Tasks.Task<VisitorRegistration.Web.VisitorRegistrationService.Visitor[]> GetCurrentVisitorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndpoint/DownloadVisitorPass", ReplyAction="http://tempuri.org/IEndpoint/DownloadVisitorPassResponse")]
        byte[] DownloadVisitorPass(System.Guid ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndpoint/DownloadVisitorPass", ReplyAction="http://tempuri.org/IEndpoint/DownloadVisitorPassResponse")]
        System.Threading.Tasks.Task<byte[]> DownloadVisitorPassAsync(System.Guid ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndpoint/GenerateVisitorPass", ReplyAction="http://tempuri.org/IEndpoint/GenerateVisitorPassResponse")]
        System.Guid GenerateVisitorPass(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndpoint/GenerateVisitorPass", ReplyAction="http://tempuri.org/IEndpoint/GenerateVisitorPassResponse")]
        System.Threading.Tasks.Task<System.Guid> GenerateVisitorPassAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEndpointChannel : VisitorRegistration.Web.VisitorRegistrationService.IEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EndpointClient : System.ServiceModel.ClientBase<VisitorRegistration.Web.VisitorRegistrationService.IEndpoint>, VisitorRegistration.Web.VisitorRegistrationService.IEndpoint {
        
        public EndpointClient() {
        }
        
        public EndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegisterVisitor(string FirstName, string LastName, string Email, string HostEmail, string IDNumber, string signature) {
            base.Channel.RegisterVisitor(FirstName, LastName, Email, HostEmail, IDNumber, signature);
        }
        
        public System.Threading.Tasks.Task RegisterVisitorAsync(string FirstName, string LastName, string Email, string HostEmail, string IDNumber, string signature) {
            return base.Channel.RegisterVisitorAsync(FirstName, LastName, Email, HostEmail, IDNumber, signature);
        }
        
        public VisitorRegistration.Web.VisitorRegistrationService.Visitor GetVisitor(int ID) {
            return base.Channel.GetVisitor(ID);
        }
        
        public System.Threading.Tasks.Task<VisitorRegistration.Web.VisitorRegistrationService.Visitor> GetVisitorAsync(int ID) {
            return base.Channel.GetVisitorAsync(ID);
        }
        
        public VisitorRegistration.Web.VisitorRegistrationService.Visitor[] GetCurrentVisitors() {
            return base.Channel.GetCurrentVisitors();
        }
        
        public System.Threading.Tasks.Task<VisitorRegistration.Web.VisitorRegistrationService.Visitor[]> GetCurrentVisitorsAsync() {
            return base.Channel.GetCurrentVisitorsAsync();
        }
        
        public byte[] DownloadVisitorPass(System.Guid ID) {
            return base.Channel.DownloadVisitorPass(ID);
        }
        
        public System.Threading.Tasks.Task<byte[]> DownloadVisitorPassAsync(System.Guid ID) {
            return base.Channel.DownloadVisitorPassAsync(ID);
        }
        
        public System.Guid GenerateVisitorPass(int ID) {
            return base.Channel.GenerateVisitorPass(ID);
        }
        
        public System.Threading.Tasks.Task<System.Guid> GenerateVisitorPassAsync(int ID) {
            return base.Channel.GenerateVisitorPassAsync(ID);
        }
    }
}
